# baseURL = "http://yuanyi-au.github.io/"

languageCode = "zh"
title = "yuanyi 的博客"
theme = "color-your-world"

copyright = "Copyright © 2021, yuanyi; All rights reserved."

enableEmoji = true
enableInlineShortcodes = true

[params]
  
  # Site description
  description = "yuanyi 的个人博客"
  
  # Author
  author = "yuanyi"
  
  [params.contact]
    
    # formspree.io Form ID
    formspreeFormId = "example"
    
    # Autocomplete [on/off] and min character length for message
    autoComplete      = false # Default is false
    messageMinLength  = 20   # Default is 140
    
    # Subject
    # You can set a single value below (and it will cease to be a dropdown),
    # BUT KEEP IT AS AN ARRAY
    # It can also be disabled entirely (and it will turn into a text field)
    subject = [ '打个招呼!', "有个问题?" ]

    # Text placeholders. As usual, comment the lines if you don't want use them
    # The "subject" below will only be used if the "subject" above doesn't exist (ie.: commented/deleted)
    [params.contact.placeholder]
      name    = "ABC 的朋友！"
      email   = "abc123@mail.com"
      subject = '打个招呼!'
      message = "随便写点什么...很乐意和你交流！"
  
  [params.style]
  
    # Dark mode as default
    # User preferences (site/system settings) will still have priority over it
    # The default is false
    isDark = true

    # Disable the use of system settings (prefers-color-scheme)
    # The default is false
    ignoreSystemSettings = true

    # Accent colors for dark and light mode respectively
    darkAccent   = "#1dbc91" # Default is "#1dbc91"
    lightAccent  = "#1f676b" # Default is "#1f676b"

    # More colors, pick as many as you want (not really sure if there's a limit)
    # Apparently these may not show up on every modern browser (ie. Firefox)
    # There's no default value. Used here just as example
    presets = [ "#225670", "#dd587c", "#902b37", "#f3a530", "#754e85", "#7fc121", "#a8314a", "#ff7433", "#3e6728", "#c063bd" ]

    # Use an icon or text for footnote return links
    # The default is false
    hasIconAsFootnoteReturnLink = true
    
    # For the social shortcode
    # Use flexbox (with flex-grow) or grid (equal width)
    # The default is false
    socialIsFlex = true
    
    # Keep anchor links hidden until it's focused/hovered
    # The default is false
    hideAnchors = true
    
    # To make use of the custom Chroma, this should be true
    # and "noClasses" (at markup.highlight) should be false
    # The default is true
    useCustomChroma = true

    # CSS animation transition when changing colors
    # The default is ".5s ease"
    changeTransition = ".3s ease"
    
    
  # For a simple 404
  [params.notFound]
    title         = "Page not found"
    description   = "This page was not found."
    paragraph     = "Nothing to see here, buddy."

  
[menu]

  [[menu.main]]
  identifier = "notes"
  name = "技术总结"
  url = "/notes/"
  weight = 10

  [[menu.main]]
  identifier = "posts"
  name = "学习经验"
  url = "/posts/"
  weight = 20

  [[menu.main]]
  identifier = "about"
  name = "关于我"
  url = "/about/"
  weight = 30
