baseURL = "https://yuanyi-au.github.io/"
DefaultContentLanguage = "zh"
languageCode = "en-us"
title = "方圆之所"
copyright = "2021 Yuanyi. All rights reserved."
theme = "diary"
# googleAnalytics = "UA-123-45"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "yuanyi's blog"
enableGitalk = false

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "yuanyi 的个人博客"  # will set 'og:description'

[params.gitalk]
  owner = "yuanyi-au"
  repo = "gitalk-comments"
  client_id = "df402f42b44a5132782e"
  client_secret = "91abb6d2335e7f2ea53a51b42eda9f6b332f283c"
[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/posts"
name = "文章"
weight = 1
[[menu.main]]
url = "/categories"
name = "分类"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/about"
name = "关于"
weight = 4
